# syntax=docker/dockerfile:experimental
# 1. start with init stage, installing everything common across all stages
# 2. deps and build stages are separated only to save on time by
#    using cached images
# 3. the final stage copies everything from the build stage into the
#    appropriate directory
#
# init stage
FROM maven:3.8.1-amazoncorretto-8 AS init

RUN yum install -y curl perl-XML-XPath \
  && yum clean all \
  && rm -rf /var/cache/yum

ARG settings


WORKDIR /opt/build/
ENV M2_HOME=/usr/local
COPY ./$settings /opt/build

# these are just to simulate the build target directories so that dependant
# dockerfiles can reference them.
RUN mkdir -p target/etc/ target/opt/ backend/target/opt/etc frontend/target
RUN touch version

# this just makes docker-compose okay with the fact that the container started
# up and then stopped "successfully".  i.e. this image is only a "build-base"
# of web and backend images.
CMD ["/bin/true"]
